# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            fuzzy bugfix
tagline:          'Random Ramblings'
description:      'The random thoughts of an aspiring programmer.'
url:              http://kwikadi.github.io
baseurl:          /

author:
  name:           'Aditya Kumar'
  url:            https://twitter.com/adik007

paginate:         5

# Custom vars
