# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            fuzzy bugfix
tagline:          'Random Ramblings'
description:      'The random thoughts of an aspiring programmer who feels suspiciously out of place.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Aditya Kumar'
  url:            https://twitter.com/adik007

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
